# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: F-Chat Rising
email: nope@nope.com
description: >- # this means to ignore newlines until "baseurl:"
  A heavily customized F-Chat 3.0 client
baseurl: "/fchat-rising" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  hearmeneigh
show_downloads: true

# Build settings
markdown: kramdown

# theme: jekyll-theme-slate
# plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - summary.psd
    - logos.psd

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: jekyll-theme-slate

changelog: https://github.com/hearmeneigh/fchat-rising/blob/master/CHANGELOG.md
installurl: https://github.com/hearmeneigh/fchat-rising/wiki

download:
  version: 1.24.2

  url: https://github.com/hearmeneigh/fchat-rising/releases/latest/download/F-Chat-Rising-%PLATFORM_TAIL%

  downloads:
    - type: win
      name: Windows (x64)
      tail: win-x64.exe
      size: 84 MB

    - type: win
      name: Windows (arm64)
      tail: win-arm64.exe
      size: 84 MB

    - type: mac
      name: MacOS (Intel)
      tail: macos-intel.dmg
      size: 80 MB
      # instructions: ./macos-install

    - type: mac
      name: MacOS (M1)
      tail: macos-m1.dmg
      size: 83 MB

    - type: linux
      name: Linux (x64)
      tail: linux-x64.AppImage
      size: 82 MB

    - type: linux
      name: Linux (arm64)
      tail: linux-arm64.AppImage
      size: 82 MB

